### ISSUE TITLE
Fails to run with `Assertion failed: Cannot call unknown function compileJSON`

### ISSUE THREAD

**Issue by hardlydifficult** [ConsenSys/truffle-security#114]
When I attempt to use `truffle-security`, it fails with the following:

```
npm view truffle-security version
1.3.0
truffle run verify
- Fetching solc version list from solc-bin
- Downloading compiler
Assertion failed: Cannot call unknown function compileJSON, make sure it is exported
Assertion failed: Cannot call unknown function compileJSON, make sure it is exported
abort("Assertion failed: Cannot call unknown function compileJSON, make sure it is exported"). Build with -s ASSERTIONS=1 for more info.
Truffle v5.0.7 (core: 5.0.7)
Node v8.11.4
```

I'm running this against this open-source repo: https://github.com/unlock-protocol/unlock/tree/master/smart-contracts
Here's an example Travis CI build: https://travis-ci.com/hardlydifficult/unlock/builds/103944395

There's not really much detail here for me to follow up on.  Anything I could provide to help investigate the issue?

**Comment by rocky** [comment]
What happens when you run `truffle compile` ?

**Comment by hardlydifficult** [comment]
Compile works, as does truffle test.

```
PS E:\unlock\smart-contracts> npx truffle compile

Compiling your contracts...
===========================
> Compiling .\contracts\PublicLock.sol
> Compiling .\contracts\interfaces\IERC721.sol
> Compiling .\contracts\interfaces\ILockCore.sol
> Compiling .\contracts\interfaces\IUnlock.sol
> Compiling .\contracts\mixins\MixinApproval.sol
> Compiling .\contracts\mixins\MixinDisableAndDestroy.sol
> Compiling .\contracts\mixins\MixinGrantKeys.sol
> Compiling .\contracts\mixins\MixinKeys.sol
> Compiling .\contracts\mixins\MixinLockCore.sol
> Compiling .\contracts\mixins\MixinLockMetadata.sol
> Compiling .\contracts\mixins\MixinNoFallback.sol
> Compiling .\contracts\mixins\MixinPurchase.sol
> Compiling .\contracts\mixins\MixinRefunds.sol
> Compiling .\contracts\mixins\MixinTransfer.sol

    > compilation warnings encountered:

/E/unlock/smart-contracts/contracts/mixins/MixinLockCore.sol:57:5: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    address _owner,
    ^------------^
,/E/unlock/smart-contracts/contracts/mixins/MixinTransfer.sol:144:5: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    address operator, // solhint-disable-line no-unused-vars
    ^--------------^
,/E/unlock/smart-contracts/contracts/mixins/MixinTransfer.sol:145:5: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    address from, // solhint-disable-line no-unused-vars
    ^----------^
,/E/unlock/smart-contracts/contracts/mixins/MixinTransfer.sol:146:5: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    uint tokenId, // solhint-disable-line no-unused-vars
    ^----------^
,/E/unlock/smart-contracts/contracts/mixins/MixinTransfer.sol:147:5: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    bytes memory data // solhint-disable-line no-unused-vars
    ^---------------^
,/E/unlock/smart-contracts/contracts/Unlock.sol:124:5: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    address _purchaser, // solhint-disable-line no-unused-vars
    ^----------------^
,/E/unlock/smart-contracts/contracts/Unlock.sol:125:5: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    uint _keyPrice // solhint-disable-line no-unused-vars
    ^------------^
,/E/unlock/smart-contracts/contracts/Unlock.sol:145:5: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    address _referrer // solhint-disable-line no-unused-vars
    ^---------------^
,/E/unlock/smart-contracts/contracts/Unlock.sol:163:5: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    uint _tokens // solhint-disable-line no-unused-vars
    ^----------^

> Artifacts written to E:\unlock\smart-contracts\build\contracts
> Compiled successfully using:
   - solc: 0.5.5+commit.47a71e8f.Emscripten.clang

PS E:\unlock\smart-contracts> npx truffle run verify
Assertion failed: Cannot call unknown function compileJSON, make sure it is exported
Assertion failed: Cannot call unknown function compileJSON, make sure it is exported
abort("Assertion failed: Cannot call unknown function compileJSON, make sure it is exported"). Build with -s ASSERTIONS=1 for more info.
Truffle v5.0.7 (core: 5.0.7)
Node v10.15.1
```

**Comment by rocky** [comment]
Interesting. So now if you run `truffle run verify` does it still try to download the compiler do you still get that error message?

**Comment by rocky** [comment]
Sorry - scratch that. I see you did run that above. 

How about if you do an `npm install -g truffle-security` instead?

**Comment by hardlydifficult** [comment]
I tried, that gives me a different error - however I'm on Windows and this looks like it may be a Windows specific issue (I've hit similar before):

```
PS E:\unlock\smart-contracts> truffle run verify
Compiling .\contracts\Migrations.sol...
Compiling .\contracts\PublicLock.sol...
Compiling .\contracts\Unlock.sol...
Compiling .\contracts\UnlockErrors.sol...
Compiling .\contracts\interfaces\IERC721.sol...
Compiling .\contracts\interfaces\ILockCore.sol...
Compiling .\contracts\interfaces\IUnlock.sol...
Compiling .\contracts\mixins\MixinApproval.sol...
Compiling .\contracts\mixins\MixinDisableAndDestroy.sol...
Compiling .\contracts\mixins\MixinGrantKeys.sol...
Compiling .\contracts\mixins\MixinKeys.sol...
Compiling .\contracts\mixins\MixinLockCore.sol...
Compiling .\contracts\mixins\MixinLockMetadata.sol...
Compiling .\contracts\mixins\MixinNoFallback.sol...
Compiling .\contracts\mixins\MixinPurchase.sol...
Compiling .\contracts\mixins\MixinRefunds.sol...
Compiling .\contracts\mixins\MixinTransfer.sol...


SyntaxError: Invalid regular expression: /C:\Users\lopop\AppData\Roaming\npm\node_modules\/: \ at end of pattern
    at new RegExp (<anonymous>)
    at C:\Users\lopop\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\cli.js:93:1
    at commandResult.then.catch.err (C:\Users\lopop\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\run.js:61:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
SyntaxError: Invalid regular expression: /C:\Users\lopop\AppData\Roaming\npm\node_modules\/: \ at end of pattern
    at new RegExp (<anonymous>)
    at C:\Users\lopop\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\cli.js:93:1
    at commandResult.then.catch.err (C:\Users\lopop\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\truffle-core\lib\run.js:61:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)

C:\Users\lopop\AppData\Roaming\npm\node_modules\truffle-security\node_modules\.cache\truffle\soljson-v0.5.5+commit.47a71e8f.js:26
(Module.asmGlobalArg,Module.asmLibraryArg,buffer);var __GLOBAL__I_000101=Module["__GLOBAL__I_000101"]=asm["__GLOBAL__I_000101"];var __GLOBAL__sub_I_ABIFunctions_cpp=Module["__GLOBAL__sub_I_ABIFunctions_cpp"]=asm["__GLOBAL__sub_I_ABIFunctions_cpp"];var __GLOBAL__sub_I_ABI_cpp=Module["__GLOBAL__sub_I_ABI_cpp"]=asm["__GLOBAL__sub_I_ABI_cpp"];var __GLOBAL__sub_I_ASTJsonConverter_cpp=Module["__GLOBAL__sub_I_ASTJsonConverter_cpp"]=asm["__GLOBAL__sub_I_ASTJsonConverter_cpp"];var __GLOBAL__sub_I_AST_cpp=Module["__GLOBAL__sub_I_AST_cpp"]=asm["__GLOBAL__sub_I_AST_cpp"];var __GLOBAL__sub_I_ArrayUtils_cpp=Module["__GLOBAL__sub_I_ArrayUtils_cpp"]=asm["__GLOBAL__sub_I_ArrayUtils_cpp"];var __GLOBAL__sub_I_AsmAnalysis_cpp=Module["__GLOBAL__sub_I_AsmAnalysis_cpp"]=asm["__GLOBAL__sub_I_AsmAnalysis_cpp"];var __GLOBAL__sub_I_CompilerContext_cpp=Module["__GLOBAL__sub_I_CompilerContext_cpp"]=asm["__GL
abort({}). Build with -s ASSERTIONS=1 for more info.
```

**Comment by hardlydifficult** [comment]
The Travis build I linked does not use `npx` and hits the first error, not this regular expression one.

**Comment by rocky** [comment]
Ok. Keep me posted. Also attach the `truffle-config.json` and `truffle.json`.

**Comment by hardlydifficult** [comment]
We only have the one, here:
https://github.com/hardlydifficult/unlock/blob/c26a403bc2059deee162bb1c67e1d9f88aaeff48/smart-contracts/truffle-config.js

**Comment by rocky** [comment]
Thanks. The scenario while reasonable (running truffle-security inside TravisCI running docker container)  while a very reasonable tihng to do, is a little bit outside hoped level complexity, especially this early on. 

 It will take me a while to see investigate what that message means and how I can replicate the problem. 

If you explainwhat the "Windows specific error" was and how you fixed it, that might save me some time. Thanks.

**Comment by hardlydifficult** [comment]
Okay, the Windows specific error (and workaround) was https://github.com/trufflesuite/truffle/issues/1796#issuecomment-470228484

Then using a global install, I get an error saying a dependency is missing:
`find-cache-dir`

Install that and now the error is about locating node modules:
```
Error: E:/unlock/smart-contracts/contracts/PublicLock.sol:5:1: ParserError: Source "openzeppelin-eth/contracts/ownership/Ownable.sol" not found: ENOENT: no such file or directory, stat 'openzeppelin-eth/contracts/ownership/Ownable.sol'
import 'openzeppelin-eth/contracts/ownership/Ownable.sol';
^--------------------------------------------------------^
,E:/unlock/smart-contracts/contracts/PublicLock.sol:6:1: ParserError: Source "openzeppelin-solidity/contracts/introspection/ERC165.sol" not found: ENOENT: no such file or directory, stat 'openzeppelin-solidity/contracts/introspection/ERC165.sol'
import 'openzeppelin-solidity/contracts/introspection/ERC165.sol';
...
```

Just to confirm, `truffle compile` still works fine.

**Comment by rocky** [comment]
Thanks for keeping with this and the update. 

Both of these problems we have seen and are fixed in the current master branch. A new release will probalby go out within 24 hours. 

(The `find-cache-dir` problem is simply a missing dependancy in package.json that we caught [in one of _our_ CI runs](https://circleci.com/gh/ConsenSys/truffle-security/499).)

**Comment by rocky** [comment]
Release 1.3.1 is out and this may address some of the problems addressed above.  (If you "watch" the project, you can get release notes sent to you)

**Comment by hardlydifficult** [comment]
Confirmed fixed.  Thanks!  I'm closing this now.
