### ISSUE TITLE
ParserError: Source "..." not found: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by aquiladev** [ConsenSys/truffle-security#119]
When I compile my project via ```truffle build``` everything works, but when I execute ```truffle run verify``` I have amount of errors on compilation:
```
ParserError: Source "openzeppelin-solidity/contracts/math/SafeMath.sol" not found:
ENOENT: no such file or directory, stat 'openzeppelin-solidity/contracts/math/SafeMath.sol'
...
```

truffle config is pretty standard
```
module.exports = {
  networks: {
    development: {
      host: "127.0.0.1", 
      port: 8545,
      network_id: "*",
    },
  },

  compilers: {
    solc: {
      version: '0.5.4'
    }
  },
  plugins: ["truffle-security"]
}
```

**Comment by imthatcarlos** [comment]
I can confirm. Need to include a relative path to the libraries for this command to work. It would be great if we didn't have to :)

**Comment by b-mueller** [comment]
Hmm, usually if the project is already built, Truffle Security shouldn't recompile it at all. Can you try to run `truffle compile` before `truffle run verify`? Or is that already implied by `truffle build`?

**Comment by imthatcarlos** [comment]
In my case, what happens is:
1. I compile the contracts successfully (excluding relative path for libs)
2. I run truffle verify
3. It seems to start to compile my contracts...
4. It doesn't produce any errors, and doesn't give the same output I was getting when I included related path to libs

**Comment by rocky** [comment]
@b-mueller things have changed slightly in the latest version. Because we don't use truffle's compile artifact but our own, a `truffle compile` doesn't directly help `truffle verify`. `truffle verify` needs to do its own compile (adjusting for imported files), but it does it using the truffle libraries as much as it can. 

But the good news is that if someone can come up with a small sample truffle project, I think we will be able to handle this without the relative path.

**Comment by tagomaru** [comment]
I got same kind of problem.

### Success case
```
import "openzeppelin-solidity/contracts/my/VulnerableParent.sol";
contract VulnerableChild is VulnerableParent {}
```

### Error case
```
import "./VulnerableParent.sol";
contract VulnerableChild is VulnerableParent {}
```

In the Error case, I got the below message.

 _"These smart contracts were not found: VulnerableChild"_

I guess it cannot consider about relative path for NPM package like zeppeline yet.

**Comment by jo-tud** [comment]
> The good news though is that if someone can come up with a small sample truffle project, I think we will be able to handle this with or without relative paths

Problem exists in this repo: https://github.com/Roger-Wu/DividendPayingToken

```
truffle compile

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

$ truffle run verify
Compiling ./contracts/DividendPayingToken.sol...
Compiling ./contracts/DividendPayingTokenInterface.sol...
Compiling ./contracts/DividendPayingTokenOptionalInterface.sol...
Compiling ./contracts/math/SafeMathInt.sol...
Compiling ./contracts/math/SafeMathUint.sol...

Error: /home/jo/projects/afp/opt/DividendPayingToken/contracts/DividendPayingToken.sol:3:1: ParserError: Source "openzeppelin-solidity/contracts/token/ERC20/ERC20Mintable.sol" not found: ENOENT: no such file or directory, stat 'openzeppelin-solidity/contracts/token/ERC20/ERC20Mintable.sol'
import "openzeppelin-solidity/contracts/token/ERC20/ERC20Mintable.sol";
^---------------------------------------------------------------------^
    at CompileError.ExtendableError (/home/jo/.nvm/versions/node/v10.11.0/lib/node_modules/truffle-security/node_modules/truffle-error/index.js:10:17)
    at new CompileError (/home/jo/.nvm/versions/node/v10.11.0/lib/node_modules/truffle-security/compat/truffle-compile/compileerror.js:12:23)
    at supplier.load.then.solc (/home/jo/.nvm/versions/node/v10.11.0/lib/node_modules/truffle-security/compat/truffle-compile/index.js:234:11)
Truffle v5.0.7 (core: 5.0.7)
Node v10.11.0

```

**Comment by b-mueller** [comment]
Same error with [ENS project](https://github.com/ensdomains/ethregistrar):

```
$ truffle run verify
Compiling ./contracts/BaseRegistrar.sol...
Compiling ./contracts/BaseRegistrarImplementation.sol...
Compiling ./contracts/DummyOracle.sol...
Compiling ./contracts/ETHRegistrarController.sol...
Compiling ./contracts/PriceOracle.sol...
Compiling ./contracts/SafeMath.sol...
Compiling ./contracts/SimplePriceOracle.sol...
Compiling ./contracts/StablePriceOracle.sol...
Compiling ./contracts/StringUtils.sol...
Compiling ./contracts/_TestDeps.sol...






Error: /Users/bernhardmueller/Projects/ethregistrar/contracts/BaseRegistrar.sol:3:1: ParserError: Source "@ensdomains/ens/contracts/ENS.sol" not found: ENOENT: no such file or directory, stat '@ensdomains/ens/contracts/ENS.sol'
import "@ensdomains/ens/contracts/ENS.sol";
^-----------------------------------------^
,/Users/bernhardmueller/Projects/ethregistrar/contracts/BaseRegistrar.sol:4:1: ParserError: Source "@ensdomains/ens/contracts/HashRegistrar.sol" not found: ENOENT: no such file or directory, stat '@ensdomains/ens/contracts/HashRegistrar.sol'
import "@ensdomains/ens/contracts/HashRegistrar.sol";
^---------------------------------------------------^
,/Users/bernhardmueller/Projects/ethregistrar/contracts/BaseRegistrar.sol:5:1: ParserError: Source "openzeppelin-solidity/contracts/token/ERC721/ERC721.sol" not found: ENOENT: no such file or directory, stat 'openzeppelin-solidity/contracts/token/ERC721/ERC721.sol'
import "openzeppelin-solidity/contracts/token/ERC721/ERC721.sol";
^---------------------------------------------------------------^
,/Users/bernhardmueller/Projects/ethregistrar/contracts/BaseRegistrar.sol:6:1: ParserError: Source "openzeppelin-solidity/contracts/ownership/Ownable.sol" not found: ENOENT: no such file or directory, stat 'openzeppelin-solidity/contracts/ownership/Ownable.sol'
import "openzeppelin-solidity/contracts/ownership/Ownable.sol";
^-------------------------------------------------------------^
    at CompileError.ExtendableError (/usr/local/lib/node_modules/truffle-security/node_modules/truffle-error/index.js:10:17)
    at new CompileError (/usr/local/lib/node_modules/truffle-security/compat/truffle-compile/compileerror.js:12:23)
    at supplier.load.then.solc (/usr/local/lib/node_modules/truffle-security/compat/truffle-compile/index.js:234:11)
Truffle v5.0.5 (
```

**Comment by aquiladev** [comment]
```
import "./../node_modules/openzeppelin-solidity/contracts/math/SafeMath.sol";
```
fixes the issue, but I expect it should work without ```./../node_modules/```

**Comment by rocky** [comment]
As it should be apparent from the above we are currnetly working on this.

**Comment by rocky** [comment]
@jo-tud With respect to  https://github.com/Roger-Wu/DividendPayingToken here is what I am seeing: 

```
$ git clone git@github.com:Roger-Wu/DividendPayingToken.git
Cloning into 'DividendPayingToken'...
remote: Enumerating objects: 124, done.        
remote: Counting objects: 100% (124/124), done.        
remote: Compressing objects: 100% (64/64), done.        
Receiving objects: 100% (124/124), 113.90 KiB | 3.93 MiB/s, done.
remote: Total 124 (delta 63), reused 115 (delta 56), pack-reused 0        
Resolving deltas: 100% (63/63), done
$ truffle compile
$ truffle compile

Compiling your contracts...
===========================
Error: Error: Could not find openzeppelin-solidity/contracts/token/ERC20/ERC20Mintable.sol from any sources; imported from /src/external-vcs/github/DividendPayingToken/contracts/DividendPayingToken.sol
    at async.whilst.error (/home/rocky/.nvm/versions/node/v10.13.0/lib/node_modules/truffle/build/webpack:/packages/truffle-compile/profiler.js:369:1)
    at /home/rocky/.nvm/versions/node/v10.13.0/lib/node_modules/truffle/build/webpack:/~/async/dist/async.js:969:1
    at next (/home/rocky/.nvm/versions/node/v10.13.0/lib/node_modules/truffle/build/webpack:/~/async/dist/async.js:5222:1)
Truffle v5.0.7 (core: 5.0.7)
Node v10.13.0
```

In your log, it looks like this previously compiled. What step am I missing to get this to `truffle compile`? 

(Since there are lots of other examples, I'll start with one of them, so this doesn't block me.)

**Comment by b-mueller** [comment]
Hey guys, Rocky is on it. Will be fixed hopefully in the next few days, fingers crossed 🤞

**Comment by jo-tud** [comment]
> In your log, it looks like this previously compiled. What step am I
missing to get this to truffle compile?
npm install

**Comment by rocky** [comment]
> Will be fixed hopefully in the next few days, fingers crossed

Current plan is to do another release over the weekend of whatever we have by then. 

There will be other small changes/improvements in that release. And as always, more to do in the pipeline.

**Comment by imthatcarlos** [comment]
Awesome, thanks for the updates guys 👍

**Comment by rocky** [comment]
For those of you who are up to it, please try out the master branch which has a proposed fix. Unless people find problems, I will be releasing this over the upcoming weekend. 

Thanks for all of your help.

**Comment by b-mueller** [comment]
FYI, try this:

```
$ npm install -g git+https://git@github.com/ConsenSys/truffle-security.git
```

**Comment by rocky** [comment]
@aquiladev release 1.3.1 is now out. (If you "watch" the project, you can get release notes sent to you). 

If this fixes the problem, close this issue. Otherwise let us know what is wrong. 

Also note that in future releases we'll be addressing things like

* EthPM packages
* globally installed NPM packages
* EIP 82

and these are marked as separate issues now.

**Comment by aquiladev** [comment]
works for me, close #119
