### ISSUE TITLE
--yaml not working

### ISSUE THREAD

**Issue by nbanmp** [ConsenSys/truffle-security#142]
`--yaml` is not working correctly. It errors with something like:

```
{ YAMLException: unacceptable kind of an object to dump [object Function]
    at writeNode (/home/nat/Dev/mythx/truffle-security/node_modules/js-yaml/lib/js-yaml/dumper.js:756:13)
    at writeBlockMapping (/home/nat/Dev/mythx/truffle-security/node_modules/js-yaml/lib/js-yaml/dumper.js:634:10)
    at writeNode (/home/nat/Dev/mythx/truffle-security/node_modules/js-yaml/lib/js-yaml/dumper.js:727:9)
    at writeBlockMapping (/home/nat/Dev/mythx/truffle-security/node_modules/js-yaml/lib/js-yaml/dumper.js:634:10)
    at writeNode (/home/nat/Dev/mythx/truffle-security/node_modules/js-yaml/lib/js-yaml/dumper.js:727:9)
    at writeBlockSequence (/home/nat/Dev/mythx/truffle-security/node_modules/js-yaml/lib/js-yaml/dumper.js:521:9)
    at writeNode (/home/nat/Dev/mythx/truffle-security/node_modules/js-yaml/lib/js-yaml/dumper.js:740:9)
    at dump (/home/nat/Dev/mythx/truffle-security/node_modules/js-yaml/lib/js-yaml/dumper.js:817:7)
    at Object.safeDump (/home/nat/Dev/mythx/truffle-security/node_modules/js-yaml/lib/js-yaml/dumper.js:823:10)
    at objects.forEach.obj (/home/nat/Dev/mythx/truffle-security/helpers.js:381:34)
    at Array.forEach (<anonymous>)
    at doReport (/home/nat/Dev/mythx/truffle-security/helpers.js:380:17)
    at Object.analyze (/home/nat/Dev/mythx/truffle-security/helpers.js:572:12)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
  name: 'YAMLException',
  reason: 'unacceptable kind of an object to dump [object Function]',
  mark: undefined,
  message: 'unacceptable kind of an object to dump [object Function]' }
```

**Comment by rocky** [comment]
Yep. As Valintin would put it, that was a "known problem", (i.e. one that I knew about was waiting for someone else to discover in the hope I would have been able to fix it first.)  

@nbanmp want to try you hand at it? It shouldn't be difficult to fix.
