### ISSUE TITLE
Verify is taking to much and fails with strange error

### ISSUE THREAD

**Issue by Ferparishuertas** [ConsenSys/truffle-security#146]
It takes more than 10 minutes stucked , and then it fails

``Writing artifacts to ./build/mythx/contracts

                      BalanceConverter |****************************************************************************************************| 100% || Elapsed: 57.5s ✓ completed
                              SafeMath |****************************************************************************************************| 100% || Elapsed: 53.1s ✓ completed
            ComplianceRegulatorService |****************************************************************************************************| 100% || Elapsed: 304.5s in progress...
                      PeriodCalculator |****************************************************************************************************| 100% || Elapsed: 55.4s ✓ completed
                      DateTimeContract |****************************************************************************************************| 100% || Elapsed: 53.0s ✓ completed
                       DateTimeLibrary |****************************************************************************************************| 100% || Elapsed: 63.0s ✓ completed
                       StringConverter |****************************************************************************************************| 100% || Elapsed: 65.3s ✓ completed
                               Ownable |****************************************************************************************************| 100% || Elapsed: 50.3s ✓ completed
           IComplianceRegulatorService |****************************************************************************************************| 100% || Elapsed: 51.7s ✓ completed
        ComplianceRegulatorServiceMock |****************************************************************************************************| 100% || Elapsed: 133.0s ✓ completed
ComplianceRegulatorServiceUnitTestMock |****************************************************************************************************| 100% || Elapsed: 55.9s ✓ completed
                           EmoneyToken |****************************************************************************************************| 100% || Elapsed: 54.7s ✓ completed
                         HoldableToken |****************************************************************************************************| 100% || Elapsed: 305.9s in progress...
                         IRBACMigrator |****************                                                                                    | 16% || Elapsed: 47.9s in progress...
                 MigratableEmoneyToken |****************************************************************************************************| 100% || Elapsed: 49.2s ✓ completed
            MigratableRegulatorService |****************************************************************************************************| 100% || Elapsed: 49.8s ✓ completed
                          MigratorRole |****************************************************************************************************| 100% || Elapsed: 62.9s ✓ completed
                       PayoutableToken |****************************************************************************************************| 100% || Elapsed: 50.4s ✓ completed
                       RedeemableToken |****************************************************************************************************| 100% || Elapsed: 49.7s ✓ completed
                        RegulatedToken |****************************************************************************************************| 100% || Elapsed: 59.0s ✓ completed
                      RegulatorService |****************************************************************************************************| 100% || Elapsed: 49.3s ✓ completed
                       ServiceRegistry |****************************************************************************************************| 100% || Elapsed: 49.6s ✓ completed
              TwoStepTransferableToken |****************************************************************************************************| 100% || Elapsed: 50.4s ✓ completed
                                 Roles |****************************************************************************************************| 100% || Elapsed: 55.5s ✓ completed
                            MinterRole |****************************************************************************************************| 100% || Elapsed: 49.5s ✓ completed
                                 ERC20 |****************************************************************************************************| 100% || Elapsed: 51.2s ✓ completed
                         ERC20Burnable |****************************************************************************************************| 100% || Elapsed: 53.7s ✓ completed
                         ERC20Detailed |****************************************************************************************************| 100% || Elapsed: 50.1s ✓ completed
                                IERC20 |****************************************************************************************************| 100% || Elapsed: 49.3s ✓ completed
                   EmoneyTokenMigrator |****************************************************************************************************| 100% || Elapsed: 53.7s ✓ completed
                    RegulatedTokenMock |****************************************************************************************************| 100% || Elapsed: 62.5s ✓ completed
                  RegulatorServiceMock |****************************************************************************************************| 100% || Elapsed: 49.2s ✓ completed
                 TokenRegulatorService |****************************************************************************************************| 100% || Elapsed: 53.1s ✓ completed

/Users/fer/Documents/PERSONAL/IOBUILDERS/em-token/node_modules/web3/lib/web3/errors.js:35
        return new Error(message);
               ^
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/Users/fer/Documents/PERSONAL/IOBUILDERS/em-token/node_modules/web3/lib/web3/errors.js:35:16)
    at XMLHttpRequest.request.onreadystatechange (/Users/fer/Documents/PERSONAL/IOBUILDERS/em-token/node_modules/web3/lib/web3/httpprovider.js:115:32)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/fer/Documents/PERSONAL/IOBUILDERS/em-token/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/fer/Documents/PERSONAL/IOBUILDERS/em-token/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpRequestError (/Users/fer/Documents/PERSONAL/IOBUILDERS/em-token/node_modules/xhr2/lib/xhr2.js:544:12)
    at ClientRequest.<anonymous> (/Users/fer/Documents/PERSONAL/IOBUILDERS/em-token/node_modules/xhr2/lib/xhr2.js:414:24)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:375:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by rocky** [comment]
What happens if you just try `truffle run verify HoldableToken` ?

**Comment by daniyarchambylov** [comment]
Closing issue due to inactivity
