### ISSUE TITLE
exception `TypeError: Cannot read property 'length' of undefined`

### ISSUE THREAD

**Issue by tintinweb** [ConsenSys/truffle-security#158]
Hi,

as noted in discord I get an exception since the last update

```console
TypeError: Cannot read property 'length' of undefined
    at Object.findLowerBound (/usr/local/lib/node_modules/truffle-security/node_modules/remix-lib/src/util.js:91:24)
    at convertFromCharPosition (/usr/local/lib/node_modules/truffle-security/node_modules/remix-lib/src/sourceMappingDecoder.js:115:19)
    at SourceMappingDecoder.convertOffsetToLineColumn (/usr/local/lib/node_modules/truffle-security/node_modules/remix-lib/src/sourceMappingDecoder.js:93:14)
    at MythXIssues.byteOffset2lineColumn (/usr/local/lib/node_modules/truffle-security/lib/issues2eslint.js:141:14)
    at MythXIssues.issue2EsLint (/usr/local/lib/node_modules/truffle-security/lib/issues2eslint.js:239:47)
    at result.messages.issues.map.issue (/usr/local/lib/node_modules/truffle-security/lib/issues2eslint.js:272:52)
    at Array.map (<anonymous>)
    at MythXIssues.convertMythXReport2EsIssue (/usr/local/lib/node_modules/truffle-security/lib/issues2eslint.js:272:34)
    at issues.map.report (/usr/local/lib/node_modules/truffle-security/lib/issues2eslint.js:289:47)
    at Array.map (<anonymous>)
    at MythXIssues.getEslintIssues (/usr/local/lib/node_modules/truffle-security/lib/issues2eslint.js:289:28)
    at objects.map.obj (/usr/local/lib/node_modules/truffle-security/helpers.js:388:31)
    at Array.map (<anonymous>)
    at doReport (/usr/local/lib/node_modules/truffle-security/helpers.js:388:16)
    at Object.analyze (/usr/local/lib/node_modules/truffle-security/helpers.js:576:12)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

```console
truffle version                                                                                                                                  ✘ 1 next ✱ ◼
Truffle v5.0.10 (core: 5.0.10)
Solidity - 0.4.24 (solc-js)
Node v11.6.0
Web3.js v1.0.0-beta.37

npm list -g | grep truffle-security
├─┬ truffle-security@1.3.2
```

ping me if you need more details about the codebase.

cheers,
tin

**Comment by hardlydifficult** [comment]
We are hitting the same trying to run truffle-security for Unlock Protocol.  Let me know if you need a repro, I could push a branch.

**Comment by nbanmp** [comment]
@elenadimitrova @tintinweb Can you try again with latest `truffle-security` release v1.3.3? (which should use armlet v2.4.0).

If this is still an issue, a repro would be appreciated.

**Comment by nbanmp** [comment]
I'm going to close this for now, If this is still not working, please reopen the issue.
