### ISSUE TITLE
Problem with path on Windows

### ISSUE THREAD

**Issue by Gershon-A** [ConsenSys/truffle-security#168]
Hello,
the new version has some path problem in windows.
After upgrade from v 1.3.1 to 1.3.2 
truffle run verify start to return errors:
```
Compiling .\contracts\MDZA.sol...
  with dependencies:
    - .\node_modules\zos-lib\contracts\Initializable.sol

{ Error: C:/Users/GershonA/Ethereum-projects/MDZA-testnet-contract/contracts/MDZA.sol:7:1: ParserError: Source "C:/Users/GershonA/Ethereum-projects/MDZA-testnet-contract/node_modules/zos-lib/contracts/Initializable.sol" not found: File import callback not supported
import "../node_modules/zos-lib/contracts/Initializable.sol";
^-----------------------------------------------------------^
    at CompileError.ExtendableError (C:\Users\GershonA\Ethereum-projects\MDZA-testnet-contract\node_modules\truffle-error\index.js:10:17)
    at new CompileError (C:\Users\GershonA\Ethereum-projects\MDZA-testnet-contract\node_modules\truffle-security\compat\truffle-compile\compileerror.js:12:23)
    at supplier.load.then.solc (C:\Users\GershonA\Ethereum-projects\MDZA-testnet-contract\node_modules\truffle-security\compat\truffle-compile\index.js:230:11)
```
Contract have 
import "../node_modules/zos-lib/contracts/Initializable.sol";
Reverted to 1.3.1 and all start work.

**Comment by nbanmp** [comment]
This may have been fixed in a recent update. Could you try the latest `truffle-security` and let us know if it is still not working?

**Comment by nbanmp** [comment]
Closing, as relative imports on windows should have been fixed in https://github.com/ConsenSys/truffle-security/pull/218 and/or a prior PR. If this is still an issue, please reopen it.
